=== emartin85/emartin85.github.io/xml/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="platos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="plato"/>
      </xs:sequence>
      <xs:attribute name="nombre" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="plato">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="imagen" type="xs:string"/>
        <xs:element name="video" type="xs:string"/>
        <xs:element name="musica" type="xs:string"/>
        <xs:element ref="ingredientes"/>
        <xs:element name="introduccion" type="xs:string"/>
        <xs:element ref="preparacion" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ingredientes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="titulo" type="xs:string"/>
        <xs:element name="ingrediente" type="xs:string" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="preparacion">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="titulo" type="xs:string"/>
        <xs:element name="paso" type="xs:string" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== emartin85/emartin85.github.io/xml/prbasic.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="platos.xsl"?>
<platos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" nombre="Principal" xsi:noNamespaceSchemaLocation="schema.xsd">
<plato id="Basico">
<nombre>Cordero al horno</nombre>
<imagen>../imagenes/platos/cordero.jpg</imagen>
<video>https://www.youtube.com/embed/Rihst-9UGww</video>
<musica>../audio/5.mp3</musica>
<ingredientes>
<titulo>
Ingredientes para Cómo preparar cordero al horno o asado
</titulo>
<ingrediente>1 pierna de cordero “pascual” de aprox. 1,5 Kg.</ingrediente>
<ingrediente>1 vaso de agua (150 ml)</ingrediente>
<ingrediente>Sal (al gusto)</ingrediente>
<ingrediente>Guarnición: lechuga, tomate y cebolla</ingrediente>
</ingredientes>
<introduccion>
Un plato que es todo un clásico en los menús de cualquier día festivo, aunque también la podemos preparar en cualquier otro momento del año.
Una receta muy sencilla que nos saldrá perfecta siempre y cuando cumplamos ciertas reglas de oro imprescindibles.
Debemos escoger una pieza de carne de calidad y paciencia, ya que la preparación y el horneado requieren al menos 2 horas de nuestro tiempo. Así prepara el asado mi madre para cualquier ocasión “especial” y fiestas de guardar, os aseguro sale de rechupete.
También tenéis otras opciones para preparar distintos tipos de cordero, una de las recetas que más triunfa es el cordero guisado con patatas.
Es el más famoso de los guisos en la mayoría de las fiestas de pueblo que conozco. Aunque tanto el cochinillo al estilo segoviano, la paletilla de cordero asado a las finas hierbas como el cabrito al horno son una de esas comidas o asados familiares de domingo para todo el año.
Como vamos a cocinar la pierna entera no necesitamos que el carnicero le haga cortes con el machete. De esta manera luego nos resultará más jugosa y no nos quedará seca.
Prepararemos la pierna de cordero tal y como se hace en un auténtico asador castellano, salvando las distancias ya que no contamos en casa con un horno de leña.
Un experto asador no utiliza ni muchos ingredientes ni sofisticados aderezos, bastará con un poco de agua para el horneado y sal para la carne.
Además intentaremos emular las condiciones del horno de leña en nuestra cocina. No me digáis que no es una receta para chuparse los dedos, ya no tenéis excusas para no cocinar en casa.
</introduccion>
<preparacion>
<titulo>
Preparación de la pierna de cordero
</titulo>
<paso>Lo primero que haremos será precalentar el horno a una temperatura alta, unos 250º C. Para que al meter el cordero no tenga que cocinarse partiendo de un entorno frío. Calor arriba y abajo.</paso>
<paso>Además vamos a poner una vasija o recipiente que aguante bien el calor del horno lleno de agua. Así vamos a conseguir humedad en el horno, que le irá genial al cordero.</paso>
<paso>Salamos bien la carne por ambos lados. Colocamos la pierna en una cazuela de barro o cerámica, con la parte interior hacia arriba.</paso>
<paso>Aunque os sobresalga un poco no os preocupéis ya que durante el horneado menguará de tamaño.</paso>
<paso>Si no disponéis de este recipiente cabría la posibilidad de cocinarlo sobre la bandeja metálica del horno. Aunque en este caso te recomiendo poner un poco de manteca en el agua. De este modo se evaporará más lentamente y no tendremos que reponerla.</paso>
<paso>Bajamos la temperatura del horno a 160º C, recordad que debe tener calor arriba y abajo sin aire.</paso>
<paso>Vertemos el vaso de agua en la base de la cazuela y metemos en el horno. La carne irá soltando su jugo sobre el agua e irá formándose poco a poco la salsa.</paso>
</preparacion>
<preparacion>
<titulo>
Horneado final y presentación del cordero al horno
</titulo>
<paso>Durante el proceso podremos apreciar cómo va goteando la carne. Para este tamaño y peso hornearemos en total 1 hora y 30 minutos. Recordad que la pieza pesa 1,5 kilos. Horneamos con la parte interior de la pierna hacia arriba durante 1 hora y 10 minutos.</paso>
<paso>En esa 1 hora y media debemos hidratar la carne unas 6 veces, aproximadamente cada 18-20 minutos.</paso>
<paso>Regamos la carne con la salsa que se va formando en la cazuela. Los últimos 20 minutos de horneado damos la vuelta a la pierna y colocamos la parte exterior de la pieza hacia arriba. Así conseguiremos un cordero con una pinta impresionante.</paso>
<paso>Subimos la temperatura a 180º C y regamos con la salsa.</paso>
<paso>Con este método conseguiremos que nos quede crujiente la piel de la pierna, mientras que el interior quedará bien jugoso. Finalizado el tiempo total retiramos del horno y servimos en la mesa.</paso>
<paso>Para el trinchado cogeremos la pierna (con un trapo) por la parte del hueso que sobresale y con un cuchillo bien afilado vamos retirando porciones de carne siguiendo la forma de la pierna, hasta que finalmente llegaremos al hueso.</paso>
<paso>Acompañamos el cordero con una guarnición de lechuga, tomate y cebolla, una ensalada sencilla para refrescar.</paso>
</preparacion>
</plato>
</platos>

=== emartin85/emartin85.github.io/xml/enavan.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="platos.xsl"?>
<platos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" nombre="Entrante" xsi:noNamespaceSchemaLocation="schema.xsd">
<plato id="Avanzado">
<nombre>Bombas de patata y carne con salsa barbacoa</nombre>
<imagen>../imagenes/platos/bomba.jpg</imagen>
<video>https://www.youtube.com/embed/LnfFVvpW6lY</video>
<musica>../audio/4.mp3</musica>
<ingredientes>
<titulo>
Ingredientes para Bombas de patata y carne con salsa barbacoa
</titulo>
<ingrediente>1 Kg de patatas gallegas medianas</ingrediente>
<ingrediente>250 g. de carne picada mixta (mitad cerdo, mitad ternera)</ingrediente>
<ingrediente>1 cebolla mediana</ingrediente>
<ingrediente>1 tomate pequeño</ingrediente>
<ingrediente>1 diente de ajo grande</ingrediente>
<ingrediente>6 cucharadas de salsa de tomate casero</ingrediente>
<ingrediente>Sal y pimienta negra recién molida (al gusto)</ingrediente>
<ingrediente>Para el rebozado: 2 huevos, 100 g. harina y 100 g. pan rallado</ingrediente>
<ingrediente>Aceite de oliva virgen extra (para freír)</ingrediente>
<ingrediente>Opcional: ½ guindilla o Salsa tabasco (al gusto)</ingrediente>
</ingredientes>
<introduccion>
Esta es una receta de carne todoterreno. Os puedo asegurar que le va a gustar a todos los paladares.
En España la podríamos llamar “patatas rellenas de carne” y así os la encontraréis en locales donde las sirvan de tapa.
Sin embargo en Latinoamérica se les llama “Bombas de carne” o “Bombas de papa”. Se preparan en la mayoría de países, aunque las que más conozco son las de Colombia, Venezuela y Argentina.
No es de extrañar al ser la patata un ingrediente muy presente en la gastronomía de toda Latinoamérica. Yo las conocí como “bombas de carne” ya hace bastantes años en mi ciudad natal Ourense.
Allí las preparan en un bar de la zona dos viños cuyos propietarios son venezolanos y las servían junto a otros manjares de ese país, como pueden ser las arepas y los tequeños de queso.
El apelativo de “bomba” viene porque al relleno de carne se le suele añadir un toque picante. A la hora de comerlas, en casa las solemos acompañar con alioli clásico o con salsa barbacoa de Salsas Choví que tanto nos gusta en casa, tal como recomiendo en la receta de hoy.
A veces le ponemos un toque picante con la salsa brava para patatas, pero siempre al gusto de cada casa. 
</introduccion>
<preparacion>
<titulo>
 Preparación de las bombas de carne
</titulo>
<paso>Comenzamos por lo que nos llevará más tiempo, cocer las patatas. Escoged patatas de tamaño similar para que se nos cocinen al mismo tiempo y estén todas en el mismo punto.</paso>
<paso>Las lavamos y las ponemos a cocer con la piel, en abundante agua (que las cubra) con sal.</paso>
<paso>He utilizado patatas de tamaño mediano, por lo que las he cocido durante 25 minutos. El tiempo en cocina no es un magnitud al 100% exacta, en este caso dependemos de la dureza de la patatas y del agua.</paso>
<paso>De todas maneras, comprobamos con un pincho o tenedor si están listas. Cuando podamos introducirlo y sacarlo sin dificultad, significa que las patatas están ya cocidas.</paso>
<paso>Las retiramos de la cazuela y las dejamos atemperar en una fuente, con separación entre ellas. Así se irán enfriando más rápidamente.</paso>
<paso>Luego trabajaremos con ellas cuando estén templadas, de modo que no quemen y podamos manejarlas sin problema. Mientras se enfrían las patatas preparamos el relleno.</paso>
<paso>Picamos la cebolla y el tomate en “brunoise” pequeña y el diente de ajo bien finito. En una sartén amplia pochamos la cebolla con un poco de aceite a fuego medio durante 10 minutos, teniendo cuidado de que no se nos queme.</paso>
</preparacion>
<preparacion>
<titulo>
Cocción de la carne para las patatas rellenas
</titulo>
<paso>Añadimos el ajo, mezclamos y sofreímos un par de minutos. Añadimos el tomate picado y removemos. Salamos al gusto y seguimos pochando todo otros 10 minutos.</paso>
<paso>Cuanto más despacio preparemos el relleno más rico quedará. Salpimentamos la carne y la echamos en la sartén. Con una cuchara de madera ayudamos a que se desmenuce bien.</paso>
<paso>Añadimos el toque de picante que puede ser media guindilla muy bien picadita o unas gotas de tabasco al gusto.</paso>
<paso>Para que la carne no nos quede muy seca echamos 6 cucharadas soperas de salsa de tomate y mezclamos bien con el resto.</paso>
<paso>Bajamos el fuego y dejamos que se cocine 10-15 minutos lentamente. Retiramos del fuego y reservamos.</paso>
<paso>Una vez templadas las patatas las pelamos fácilmente y las convertimos en puré con la ayuda de un tenedor o similar. Queremos conseguir una masa homogénea y sin grumos.</paso>
<paso>Para conseguir una textura adecuada no dejéis que lleguen a enfriarse del todo, si no será una tarea harto complicada.</paso>
</preparacion>
<preparacion>
<titulo>
Fritura y presentación final de las patatas rellenas
</titulo>
<paso>Para el montaje de las “bombas” he utilizado un pequeño truco de madre. Poner un poco de papel aluminio para trabajar sobre él.</paso>
<paso>El tamaño final será como el de una pelota de tenis, podéis hacerlas más pequeñas pero os darán más trabajo.</paso>
<paso>Ponemos una lámina de papel de aluminio, cogemos un poco de puré de patata y lo aplastamos con las manos. Hasta dejarlo de un grosor de 1,5 a 2 centímetros.</paso>
<paso>Colocamos en el centro un par de cucharadas de relleno (que estará templado). Subimos un poco de los lados el papel para comenzar a cerrar la bola.</paso>
<paso>Retiramos del aluminio, colocamos sobre la palma de la mano. Vamos cerrando con cuidado, dejando el relleno bien en el centro. Con la pelota hecha, damos forma de esfera con las manos y reservamos. Repetimos el proceso con el resto.</paso>
<paso>Para el rebozado podemos utilizar dos versiones. En algunos países mezclan los 2 huevos batidos con 3 cucharadas de harina, removiendo bien hasta que no queden grumos.</paso>
<paso>Para probar he rebozado una bomba con este método y el resto con el más habitual en casa, usando además pan rallado.</paso>
<paso>Batimos los huevos, y disponemos la harina y el pan rallado en platos individuales.</paso>
<paso>En una sartén alta vertemos abundante aceite de oliva y calentamos. Cuando alcance temperatura, pasamos las bombas primero por harina, luego huevo y finalmente pan rallado.</paso>
<paso>Las freímos de una en una en aceite bien caliente por todas partes. Las movemos regularmente para que no se nos queme el rebozado.</paso>
</preparacion>
</plato>
</platos>

=== emartin85/emartin85.github.io/xml/poavan.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="platos.xsl"?>
<platos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" nombre="Postres" xsi:noNamespaceSchemaLocation="schema.xsd">
<plato id="Avanzado">
<nombre>Filloas caramelizadas rellenas de crema pastelera</nombre>
<imagen>../imagenes/platos/filloas.jpg</imagen>
<video>https://www.youtube.com/embed/0xaftW5jt1U</video>
<musica>../audio/10.mp3</musica>
<ingredientes>
<titulo>
Ingredientes para Filloas caramelizadas rellenas de crema pastelera
</titulo>
<ingrediente>4 yemas de huevo (crema pastelera)</ingrediente>
<ingrediente>100 g de azúcar (crema pastelera)</ingrediente>
<ingrediente>50 g de maicena (crema pastelera)</ingrediente>
<ingrediente>1/2 l de leche entera infusionada (crema pastelera)</ingrediente>
<ingrediente>1 vaina de vainilla, 1 rama de canela en rama y 1 limón (para infusionar la leche)</ingrediente>
<ingrediente>4 huevos grandes (filloas)</ingrediente>
<ingrediente>750 ml de leche entera (filloas)</ingrediente>
<ingrediente>1 pellizco de sal (filloas)</ingrediente>
<ingrediente>400 g de harina de trigo (filloas)</ingrediente>
<ingrediente>50 g de mantequilla derretida (filloas)</ingrediente>
<ingrediente>Azúcar glass (en polvo) y un toque de canela (para el caramelizado final)</ingrediente>
</ingredientes>
<introduccion>
Una de las recetas de postre más preparada y consumida en Galicia durante todo el año son las filloas.
El postre de hoy va un poco más allá, son las típicas filloas de leche como las que podéis encontrar en todas las pastelerías o restaurantes de Ourense pero rellenas de crema pastelera.
Además le hemos aportado un caramelizado posterior con soplete (quedan mucho más ricas con este toque similar a la crema catalana).
Cuando hablamos de filloas o frixuelos asturianos, la mayoría dice que son diferentes pero la verdad es que son muy parecidos.
Las filloas, freixó, afilloa, filloga o fisuelo (varía el nombre dependiendo de la región), son uno de los productos más famosos de la gastronomía gallega.
Un postre muy famoso del entroido, tal es así que las auténticas incorporan caldo en su preparación y en la Matanza, sangre de cerdo en su preparación.
No se entiende un Entroido o Carnaval sin ellas y las orejas de Carnaval. Quizás este sea el postre más consumido en todas las casas de Galicia ya que se han convertido en un postre típico en época de Don Carnal.
Hay muchas recetas para prepararlas, pero todas utilizan al menos harina, leche, huevos y sal.
El secreto de las más exquisitas se encuentra en el arte de mantener la temperatura constante de la sartén, piedra o plancha de fundición (filloeira) donde se cuecen.
También depende del grosor, cuanto más finas más ricas. A diferencia de las crepes de Bretaña francesa en Galicia las filloas no se hacen nunca con harina integral.
</introduccion>
<preparacion>
<titulo>
Preparación de la crema pastelera. Aromatiza la leche
</titulo>
<paso>Lo primero es preparar los ingredientes con los que vamos a aromatizar la leche. Lavamos muy bien el limón y pelamos su piel de manera fina, sin mucho blanco que luego nos amargue el postre. Abrimos la vaina de vainilla  y sacamos las semillas que reservaremos para añadir más tarde a la leche. Si no encontráis vaina de vainilla la podéis sustituir por esencia de vainilla, le dará el toque aunque no será igual.</paso>
<paso>Separamos un vasito de leche del total que vamos a emplear y lo reservamos. Calentamos el resto de la leche en un cazo a fuego medio casi hasta el punto de ebullición. Bajamos la temperatura y retiramos del fuego.</paso>
<paso>Añadimos las semillas de vainilla, la piel del limón y por último la canela en rama partida por la mitad. Dejamos todo en reposo infusionando durante 10 minutos.</paso>
</preparacion>
<preparacion>
<titulo>
Preparación de la crema pastelera para el relleno de las filloas
</titulo>
<paso>Mezclamos la maicena en el vaso de leche tibia y juntamos hasta que no tenga nada de grumos.</paso>
<paso>Si es necesario le pasamos la batidora o usamos unas varillas. Separamos las yemas de las claras.</paso>
<paso>Ponemos las yemas en un bol y batimos con el azúcar hasta que espumee.</paso>
<paso>Añadimos el vaso de leche con la fécula de maíz disuelta. Volvemos a batir hasta que no queden grumos, tiene que quedar una masa homogénea. Reservamos.</paso>
<paso>Colamos la leche infusionada y la volvemos a añadir al cazo, calentamos a media ebullición. Añadimos la crema del paso anterior.</paso>
<paso>Lo vamos añadiendo poco a poco y mezclando con unas varillas o una cuchara de madera sin parar hasta que espese. No debe hervir en ningún momento.</paso>
<paso>La textura de la crema debe estar ligeramente espesa y sin grumitos. Es muy importante no dejar de remover pues puede llegar a quemarse o pegarse a la cazuela.</paso>
<paso>El secreto como en casi todas las recetas es tener paciencia y no dejar de remover siempre para el mismo lado hasta que quede una crema homogénea.</paso>
<paso>Añadimos la mantequilla para acabar de mantecar, hace más crema y le da brillo. Dejamos enfriar totalmente para empezar con la masa de las filloas.</paso>
</preparacion>
<preparacion>
<titulo>
Preparación de la masa de las filloas
</titulo>
<paso>En un bol grande echamos la leche, la harina, un pellizco de sal, la mantequilla en pomada y los huevos.</paso>
<paso>Batimos todo con la batidora sin que queden grumos. Dejamos reposar una hora para que espese ligeramente (aunque la crema debe quedar suelta).</paso>
<paso>En una sartén antiadherente o crepera caliente untamos un poco de mantequilla, tocino o unas gotas de aceite.</paso>
<paso>Si empleamos manteca o mantequilla la podemos manipular con un tenedor. Si empleáis mantequilla  un truco fácil es partir un poco en forma de barra, envolver un extremo en papel de aluminio para poder sujetarla y untar con el otro la sartén.</paso>
<paso>Untamos toda la sartén de esta manera hasta que se derrita la mantequilla. No debe de quedar muy grasienta pero tampoco debemos quedarnos cortos.</paso>
<paso>Si empleáis tocino es más sencillo, sólo tenéis que pincharlo con un tenedor e ir frotando la crepera-filloeira hasta que quede bien impregnada.</paso>
<paso>Cuando la sartén esté caliente echamos la crema de manera que cubra todo el fondo, solamente la justa para que queden finas.</paso>
<paso>Suelo emplear una crepera, perfecta por un diseño liso al estilo de las filloeiras gallegas.</paso>
<paso>Con una distribución de calor inmediata y así poder controlar el grosor de la filloa sin pasarme y me quedan todas iguales. Además está hecha de hierro que es un perfecto conductor de calor, de forma que puedo cocinar con el fuego mediano o bajo.</paso>
<paso>La medida de crema es la de un cucharón (no echéis demasiado porque os saldrán muy gordas). Levantamos, inclinamos y giramos la sartén para que la crema se reparta por todo el fondo.</paso>
</preparacion>
<preparacion>
<titulo>
Preparación de las filloas y presentación final
</titulo>
<paso>La filloa empezará a cocerse al momento, la tendremos como 10-15 segundos a temperatura media-baja.</paso>
<paso>Cuando los bordes empiecen a doblarse hacia arriba (porque están tostaditos) es el momento adecuado para darle la vuelta con el tenedor o con los dedos.</paso>
<paso>Cuando le deis la vuelta si el tono del tostado no es dorado será por falta de huevo, podéis aprovechar para añadir otro más a la crema.</paso>
<paso>Doramos por ambos lados y vamos apilando en un plato grande. Recordad que la primera filloa es de prueba (yo me la zampo en el momento).</paso>
<paso>Es la más grasienta porque la sartén va cogiendo el punto de temperatura y el grado de grasa de la mantequilla o grasa a emplear. La segunda filloa suele salir ya perfecta.</paso>
<paso>Continuamos haciendo las filloas hasta que se acabe la crema. Si lo del tenedor no se os da bien podéis usar el truco de dar la vuelta a la filloa con un plato. Como si fuese una tortilla de patata, según se coge práctica deja de ser necesario. Reservamos en un plato.</paso>
<paso>El paso final es el de la presentación, rellenamos cada filloa con dos cucharadas a tope de crema pastelera.</paso>
<paso>Enrollamos y espolvoreamos con azúcar en polvo.</paso>
<paso>Quemamos el azúcar con un soplete de cocina hasta que caramelice, si las servimos inmediatamente.</paso>
</preparacion>
</plato>
</platos>

=== emartin85/emartin85.github.io/xml/plantilla.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="platos.xsl"?>
<platos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" nombre="Postres" xsi:noNamespaceSchemaLocation="schema.xsd">
<plato id="Basico">
<nombre>Nombre del plato</nombre>
<imagen>../imagenes/platos/"plato".jpg</imagen>
<video>https://www.youtube.com/embed/"enlace"</video>
<musica>../audio/"numero".mp3</musica>
<ingredientes>
<titulo>

</titulo>
<ingrediente>

</ingrediente>
</ingredientes>
<introduccion>

</introduccion>
<preparacion>
<titulo>

</titulo>
<paso>

</paso>
</preparacion>
<preparacion>
<titulo>

</titulo>
<paso>

</paso>
</preparacion>
<preparacion>
<titulo>

</titulo>
<paso>

</paso>
</preparacion>
</plato>
</platos>

=== emartin85/emartin85.github.io/xml/enapre.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="platos.xsl"?>
<platos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" nombre="Entrante" xsi:noNamespaceSchemaLocation="schema.xsd">
<plato id="Aprendiz">
<nombre>Croquetas de queso</nombre>
<imagen>../imagenes/platos/croqueso.jpg</imagen>
<video>https://www.youtube.com/embed/Vtjr9iXCU10</video>
<musica>../audio/3.mp3</musica>
<ingredientes>
<titulo>
Ingredientes para Croquetas de queso
</titulo>
<ingrediente>350 ml. leche entera</ingrediente>
<ingrediente>50 g. de harina de trigo común 00</ingrediente>
<ingrediente>35 g. de mantequilla</ingrediente>
<ingrediente>50 g. de queso Roquefort (o mezcla de tus quesos preferidos)</ingrediente>
<ingrediente>1 huevo</ingrediente>
<ingrediente>Sal y pimienta negra molida (al gusto de cada casa)</ingrediente>
<ingrediente>Para rebozar: harina, huevo y pan rallado</ingrediente>
<ingrediente>Para la fritura: aceite suave para freír, oliva virgen extra o girasol</ingrediente>
</ingredientes>
<introduccion>
Puede que para muchos sea una sorpresa saber que el origen de las croquetas no es español si no francés.
La palabra croqueta, proviene de la voz francesa croquer (crujir) y de su diminutivo croquette.
El primer documento escrito que se conoce donde aparece nombrada esta técnica culinaria, es en 1691, donde el cocinero del por entonces rey Luís XIV, deja la receta por escrito y para la posteridad.
Se trataban de unas croquetas de trufa, mollejas y crema de queso, una delicia por cierto.
En el blog tenemos una gran variedad de croquetas en nuestras recetas de aperitivos, perfectas como un primero o incluso como una cena de rechupete. Con toda esta muestra de croquetas casi podemos decir que hemos mejorado la receta francesa.
Se trata de un plato que los españoles hemos sabido llevar mucho más allá que de una simple receta de aprovechamiento. Transformándose en todo un culto culinario en nuestro país.
Los ingredientes son tan variados como platos que se puedan preparar en cocina, a partir de ellos combinándolos con una buena salsa bechamel, podremos formar croquetas de todo tipo de tamaños y formas.
Una receta de croquetas francesa por excelencia, croquetas de queso, en esta caso roquefort. Tendremos que probar la proporción de queso que más se adapte a nuestro gusto.
</introduccion>
<preparacion>
<titulo>
Preparación de la masa de las croquetas de queso
</titulo>
<paso>En una sartén o cazuela ancha calentamos la mantequilla hasta que se haya derretido.</paso>
<paso>Añadimos la harina y, con la ayuda de unas varillas, removemos hasta que veamos que se haya integrado con toda la grasa de la mantequilla. Sin parar de remover y, a fuego medio, cocinamos la harina durante 1 o 2 minutos.</paso>
<paso>Vamos incorporando la leche a la cazuela, primero en pequeñas cantidades, integrándola bien con la harina antes de añadir más. Este paso de ir añadiendo la leche poco a poco. Es fundamental ya que así nos aseguraremos de que la crema no tendrá grumos.</paso>
<paso>Sin parar de remover integramos toda la leche y salpimentamos al gusto.</paso>
<paso>Seguimos cocinando la salsa, a temperatura media baja, durante unos 5 minutos, sin parar de remover.</paso>
<paso>Añadimos el queso desmigado y seguimos removiendo hasta que se haya disuelto en la crema. Apagamos el fuego y dejamos que la salsa se temple ligeramente antes de añadir el huevo.</paso>
<paso>Incorporamos el huevo y mezclamos bien para que se integre en la salsa. Volvemos a poner al fuego a temperatura media/baja durante unos minutos para que se cocine el huevo ya mezclado sin cuajarse.</paso>
<paso>Retiramos la crema del fuego y la vertemos en una fuente.</paso>
<paso>Dejamos que se enfríe la mezcla y la tapamos con papel transparente.</paso>
<paso>Guardamos la crema en el frigo, lo mejor será que la dejemos de un día para otro, para que se solidifique. Así será más manejable para poder preparar las croquetas.</paso>
</preparacion>
<preparacion>
<titulo>
Rebozado, fritura y presentación final de las croquetas de queso
</titulo>
<paso>Con la crema ya fría preparamos 3 boles con harina, huevo y pan rallado, respectivamente.</paso>
<paso>Formamos las croquetas con las manos, dándoles la forma que más nos guste, la ovalada y alargada más tradicional, o redonditas como he hecho en esta ocasión.</paso>
<paso>Pasamos las bolitas por harina, huevo y pan rallado, en este orden y las vamos reservando hasta que las tengamos todas listas.</paso>
<paso>En este punto podemos hacer dos cosas. Freírlas para disfrutarlas en el momento o congelarlas para poder hacerlo cuando queramos.</paso>
<paso>Admiten la congelación perfectamente. Sólo tendremos que retirarlas del frigo y ponerlas directamente a freír. Sin descongelar, con el aceite bien caliente, cuando queramos prepararlas.</paso>
<paso>En una cazuela de paredes altas, calentamos abundante aceite suave, para freír.</paso>
<paso>Vamos cocinando las croquetas a fuego alto, regulando la temperatura para evitar que se nos quemen.</paso>
<paso>Retiramos a un plato con papel absorbente, para eliminar el exceso de aceite. Servimos directamente, recién hechas.</paso>
</preparacion>
</plato>
</platos>
