=== emartin85/emartin85.github.io/xml/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="platos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="plato"/>
      </xs:sequence>
      <xs:attribute name="nombre" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="plato">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="imagen" type="xs:string"/>
        <xs:element name="video" type="xs:string"/>
        <xs:element name="musica" type="xs:string"/>
        <xs:element ref="ingredientes"/>
        <xs:element name="introduccion" type="xs:string"/>
        <xs:element ref="preparacion" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ingredientes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="titulo" type="xs:string"/>
        <xs:element name="ingrediente" type="xs:string" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="preparacion">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="titulo" type="xs:string"/>
        <xs:element name="paso" type="xs:string" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== emartin85/emartin85.github.io/xml/enbasic.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="platos.xsl"?>
<platos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" nombre="Entrantes" xsi:noNamespaceSchemaLocation="schema.xsd">
<plato id="Basico">
<nombre>Patatas alioli</nombre>
<imagen>../imagenes/platos/alioli.jpg</imagen>
<video>https://www.youtube.com/embed/DX4U9u9u930</video>
<musica>../audio/2.mp3</musica>
<ingredientes>
<titulo>
Ingredientes para Patatas alioli
</titulo>
<ingrediente>5 patatas medianas especiales para cocer (1 por persona, más una de regalo)</ingrediente>
<ingrediente>Sal (un buen puñado) para la cocción de las patatas</ingrediente>
<ingrediente>Agua para la cocción y un chorrito de vinagre de vino</ingrediente>
<ingrediente>Para la opción del alioli clásico: 6 dientes de ajo grandes de tamaño similar</ingrediente>
<ingrediente>350 ml de aceite de oliva virgen extra (se puede sustituir con aceite de oliva suave)</ingrediente>
<ingrediente>Una pizca de sal gorda</ingrediente>
<ingrediente>1 cucharada de zumo de limón (opcional)</ingrediente>
<ingrediente>Un poco de perejil fresco bien picado para mezclar</ingrediente>
</ingredientes>
<introduccion>
Si vais a algún bar de España, seguro que encontraréis esta tapa fácil, sabrosa y económica, nos referimos a las famosas patatas al alioli.
Es un clásico aperitivo de cortesía que nos sirven en muchos bares al pedir una cerveza o un vino. Si sois unos apasionados de la salsa alioli las patatas le van que ni pintadas.
Rivalizan en Madrid directamente con las patatas bravas y puedo asegurar que las patatas alioli de la mayoría de los bares rara vez es alioli de verdad, sino más bien mayonesa con ajo. Cuando probéis esta receta en casa os aseguro que vais a alucinar.
Podéis preparar vuestras patatas al alioli en casa sin problema, pues es una tapa muy fácil de preparar, lo fundamental es la calidad de los ingredientes, son pocos y baratos, pero deben ser buenos.
Las patatas que sean especiales para cocer, y el alioli lo podéis hacer casero o apostar por el clásico alioli de Salsas Choví. Os contamos la mejor forma de hacerlas y los trucos para que estén incluso mejor que en vuestro bar de siempre.
</introduccion>
<preparacion>
<titulo>
Preparación de las patatas. Cocción
</titulo>
<paso>Lavamos las patatas antes de incorporarlas a una cazuela con agua ligeramente salada.</paso>
<paso>Añadimos un chorrito de vinagre pues ayuda a que no reviente la piel. Aunque lo fundamenta es no pasarse en la cocción.</paso>
<paso>Cocemos las patatas sin pelar durante unos 25-30 minutos, hasta que estén tiernas. Las podéis pinchar con un tenedor para comprobar el punto de cocción.</paso>
<paso>Una vez cocidas las patatas, les cambiamos el agua caliente por agua fría y esperamos a que se templen. Es importante que se templen antes de proceder a retirarles la piel.</paso>
<paso>Después las pelamos y las cortamos en trozos irregulares grandes, dejándolas en un bol para que se enfríen bien.</paso>
<paso>Podemos preparar el alioli o all-i-oli casero siguiendo nuestra receta tradicional y haciéndolo solo con ajo y aceite, sin huevo y en mortero. Otra opción es preparar una mayonesa con un toque de ajo. Debe de quedar ligera para que pueda mezclar bien con las patatas.</paso>
<paso>Por último, también una opción válida, es comprar un alioli de confianza, el de Salsas Choví, os aseguro que es de nota.</paso>
</preparacion>
<preparacion>
<titulo>
Preparación del alioli casero
</titulo>
<paso>Para hacer esta salsa necesitamos un mortero (imprescindible que sea de mármol o loza) para poder emulsionar el ajo. Se compone de dientes de ajo y sal gorda que se machacan hasta conseguir una pasta.</paso>
<paso>Pelamos los dientes de ajo y los machamos en el mortero mezclados con una pizca de sal gorda. Deben picarse bien los ajos con una maza de madera hasta lograr una fina pasta.</paso>
<paso>Seguidamente con una mano se va vertiendo lentamente el aceite de oliva virgen extra en el mortero. Siempre de forma que caiga un fino hilillo fino, sin dejar de mover.</paso>
<paso>Con la otra mano se debe remover la mezcla con la maza sobre el mortero sin parar. Siempre en el mismo sentido de giro.</paso>
<paso>Poco a poco el aceite de oliva irá ligando con los ajos e irá aumentando de volumen progresivamente.</paso>
<paso>Al final quedará como una crema espesa que permanece compacta aun cuando inclinamos el mortero.</paso>
<paso>El aceite de oliva lo añadimos muy poco a poco ligándolo bien antes de seguir echando más. Así conseguimos que se logre la pasta deseada.</paso>
</preparacion>
<preparacion>
<titulo>
Presentación final de las patatas al alioli
</titulo>
<paso>Añadimos la salsa alioli y el perejil picadito. Reservamos un poquito más para espolvorear por encima en el momento de servir.</paso>
<paso>Mezclamos suavemente dando movimientos envolventes y procurando que no se nos partan.</paso>
<paso>Debemos tener cuidado de no romper ni machacar las patatas durante esta operación.</paso>
<paso>Es mejor ir añadiendo el alioli poco a poco, para no pasarnos con la cantidad. Deben de quedar unas patatas bien impregnadas del alioli y bien distribuido.</paso>
<paso>Refrigeramos las patatas alioli, cubiertas con papel transparente durante 30 minutos antes de servir.</paso>
<paso>Pasamos las patatas con el alioli a una fuente de servir, ponemos un poquillo más de perejil picado y a comer.</paso>
</preparacion>
</plato>
</platos>

=== emartin85/emartin85.github.io/xml/pobasic.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="platos.xsl"?>
<platos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" nombre="Postres" xsi:noNamespaceSchemaLocation="schema.xsd">
<plato id="Basico">
<nombre>Tiramisú</nombre>
<imagen>../imagenes/platos/tiramisu.jpg</imagen>
<video>https://www.youtube.com/embed/ksO2FCsPpsA</video>
<musica>../audio/8.mp3</musica>
<ingredientes>
<titulo>Ingredientes para Tiramisú. Receta italiana</titulo>
<ingrediente>400 g. de queso-crema Mascarpone</ingrediente>
<ingrediente>6 huevos (de los que empleamos 6 yemas para el sabayón y 4 claras para montar)</ingrediente>
<ingrediente>150 g. de azúcar glas (100 g. para las yemas y 50 g. para las claras)</ingrediente>
<ingrediente>300 g. de bizcochos de soletilla</ingrediente>
<ingrediente>4 cucharadas de Amaretto o el licor que nos guste</ingrediente>
<ingrediente>100 g. de cacao en polvo</ingrediente>
<ingrediente>175 g. de café fuerte (el que más nos guste)</ingrediente>
<ingrediente>1 pellizco de sal para montar las claras</ingrediente>
</ingredientes>
<introduccion>
El tiramisú es quizás una de las recetas de postres más famosas de la cocina italiana.
Uno de los dulces italianos por excelencia y se ha convertido en una receta tradicional italiana a pesar de ser bastante reciente.
Su origen se sitúa en la región de Véneto en los años 50 y no llevaba marcarpone ni licor, sin queso ¿sorprendidos?
El tiramisú tal como lo conocemos ahora en su tiempos era mucho más sencillo. Consistía en un dulce fortalecedor y de inmediato efecto gracias a la cantidad de glúcidos que incorporaba.
En aquellos tiempos sólo empleaban 5 ingredientes: huevos y azúcar batidos, bizcochos Savoiardi mojados en café expresso y cacao en polvo.
El queso lo añadieron después pues la crema de queso ralentiza la digestión, obteniendo el efecto contrario de somnolencia.
La evolución y posterior reconocimiento se produjo gracias a la cadena de restaurantes Toulá en 1968 que dio a conocer en toda Italia este postre delicado, sencillo y muy cremoso.
</introduccion>
<preparacion>
<titulo>Preparación de la crema sabayón</titulo>
<paso>Calentamos agua en una cazuela grande, debe estar caliente pero sin llegar a hervir. Mientras se calienta el agua vamos separando las yemas de las claras y apartamos en una taza. Las claras las vamos a montar posteriormente, reservamos.</paso>
<paso>Los huevos deben ser frescos y hay que manipularlos a temperatura ambiente. Vamos a usar azúcar glass con un toque de vainilla, lo mezclamos en un cuenco metálico con todas las yemas.</paso>
<paso>Empezamos batiendo en el cuenco fuera del agua y cuando comience a espumear introducimos el cuenco en la cazuela con el agua caliente.</paso>
<paso>Una vez dentro batimos con unas varillas manualmente o con las de la batidora hasta que las yemas doblen de tamaño. Vamos añadiendo poco a poco las cuatro cucharadas de amaretto y mezclando de manera envolvente hasta que estén incorporadas a la crema.</paso>
<paso>Después de mezclar todo sacamos del baño maría y seguimos en frío hasta que nos quede una crema esponjosa y compacta. Reservamos para el montaje del tiramisú.</paso>
</preparacion>
<preparacion>
<titulo>Preparación del tiramisú italiano</titulo>
<paso>Batimos el queso hasta que quede cremoso (lo mejor es batirlo a temperatura ambiente). Mezclamos con la crema sabayón. Mezcladlo suavemente sin que se baje la crema, queremos conseguir es una crema esponjosa.</paso>
<paso>Montamos las claras que tenemos reservadas a punto de nieve. Para ello introducimos las claras a temperatura ambiente en un bol en el que no haya ningún resto de grasa o no subirán.</paso>
<paso>Les añadimos un pellizco de sal y empezamos a batir. Mientras batimos vamos añadiendo el azúcar en polvo. Batimos hasta que las claras suban y queden firmes. Luego manejamos el merengue con una espátula de silicona.</paso>
<paso>Añadimos las claras montadas a la crema anterior. Mezclamos de manera envolvente y con cuidado hasta que quede todo integrado. Y ya tenemos lo más importante: la crema base del tiramisú. Por si sola está que te mueres, nunca he podido evitar comerme una o dos cucharadas.</paso>
<paso>Lo demás es pan comido, ponemos una cafetera italiana con un buen café. El que más nos guste, y una vez preparado lo dejamos enfriar. Cuando este frío asustamos los bizcochos con el café, tampoco tienen que soltar mucho líquido.</paso>
</preparacion>
<preparacion>
<titulo>Presentación final del tiramisú italiano</titulo>
<paso>Ponemos una capa de bizcochos de soletilla y otra de crema, así dos o tres veces y acabamos con crema.</paso>
<paso>El último paso es el del toque del cacao, imprescindible que sea cacao de calidad y amargo. Este ingrediente es el que da ese contraste tan importante en este postre.</paso>
<paso>Lo espolvoreamos sobre el postre con un colador para que no queden grumillos. Yo suelo dejar este paso para el final de todo. Justo antes de presentarlo a los invitados, porque al enfriar el cacao tiene peor presentación.</paso>
<paso>Y lo fundamental, metedlo a la nevera para que enfríe. Yo lo dejo siempre de un día para otro.</paso>
</preparacion>
</plato>
</platos>

=== emartin85/emartin85.github.io/xml/prapre.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="platos.xsl"?>
<platos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" nombre="Principal" xsi:noNamespaceSchemaLocation="schema.xsd">
<plato id="Aprendiz">
<nombre>Arroz marinero con merluza</nombre>
<imagen>../imagenes/platos/marinero.jpg</imagen>
<video>https://www.youtube.com/embed/2ygFdRAZk0g</video>
<musica>../audio/6.mp3</musica>
<ingredientes>
<titulo>
Ingredientes para Arroz marinero con merluza
</titulo>
<ingrediente>1/2 kg. de merluza (fresca o congelada)</ingrediente>
<ingrediente>300 g. de arroz de grano redondo SOS</ingrediente>
<ingrediente>1 l. de caldo de pescado o agua</ingrediente>
<ingrediente>2 patatas para cocer</ingrediente>
<ingrediente>1 pimiento verde y otro rojo</ingrediente>
<ingrediente>2 tomates grandes y maduros</ingrediente>
<ingrediente>1 diente de ajo</ingrediente>
<ingrediente>Perejil fresco</ingrediente>
<ingrediente>2 pimientos choriceros (o 1 cucharadita de pulpa de pimiento choricero)</ingrediente>
<ingrediente>1 hojita de laurel</ingrediente>
<ingrediente>Pimentón dulce</ingrediente>
<ingrediente>Aceite de oliva virgen extra</ingrediente>
<ingrediente>Sal (al gusto de cada casa)</ingrediente>
</ingredientes>
<introduccion>
Un arroz con todo el sabor al mar, pero donde todos los ingredientes son muy pequeñitos, el pescado sin una espina y muy fácil de comer.
Por eso, es perfecto para preparar en casa si tenéis niños que no le guste el pescado, en el formato tradicional (muy rico) pero que no entra por los ojos.
Parece que las palabras niño y pescado no se llevan bien, pero es necesario que lo coman y forme parte de sus menús semanales, por eso os recomiendo este arroz meloso marinero con un punto intermedio entre el caldoso y el seco.
Una receta sencilla y muy sabrosa con la que quedaremos como reyes un domingo o en una ocasión especial.
Lo hemos cocinado con un arroz SOS redondo que nunca nos falla. El resultado es espectacular porque la mezcla de sabores es realmente deliciosa. Ya veréis como en casa no dejan ni un grano de arroz en el plato.
</introduccion>
<preparacion>
<titulo>
Antes de cocinar. Hidratar el pimiento choricero
</titulo>
<paso>El pimiento choricero va a dar un punto y aroma delicioso al arroz. Hay dos posibilidades, o bien comprar ya la pulpa (la venden en todos los supermercados) o hidratar los pimientos en casa.</paso>
<paso>En caso de la primera opción, es sencillo, sólo abrir el bote. Pero para la segunda, para poder retirar la pulpa lo introducimos en un recipiente con agua durante una hora antes de cocinarlo.</paso>
<paso>Cuando el pimiento choricero lleva al menos una hora en el agua, lo abrimos, desechamos las pepitas y con la ayuda de una cuchara retiramos la pulpa raspando la piel. Al estar reblandecido ésta saldrá perfectamente. Reservamos.</paso>
<paso>En cuanto a los tomates hay que sacarles la piel y picarlos. Para eso los escaldamos en agua y los cortamos en trozos muy pequeños. Así al cocinarlos quedan totalmente desechos.</paso>
</preparacion>
<preparacion>
<titulo>
Preparación del arroz con merluza
</titulo>
<paso>Lo primero que hacemos es revisar la merluza. No queremos ninguna espina. Lo mejor es comprar un lomo de merluza grande fresco o lomos de merluza congelado (que ya viene sin espinas). Si es fresco, pedir al pescadero que lo limpie para la receta.</paso>
<paso>En casa sólo tenemos que desmigar, es decir separar la merluza en hilos (también podéis cortar en trocitos).</paso>
<paso>En una cazuela rehogamos la merluza en un poco de aceite de oliva virgen extra y una vez dorado (3- 5 minutos), reservamos.</paso>
<paso>Mientras tanto pelamos y cortamos las patatas. Asimismo cortamos en tiras el pimiento rojo y el pimiento verde.</paso>
<paso>A continuación sofreímos en el mismo aceite de la merluza, las patatas cortadas en trozos pequeños junto con los pimientos. Lo dejamos pochar 10 minutos a fuego lento.</paso>
<paso>Una vez doradas las patatas y los pimientos, echamos la pulpa extraída del pimiento choricero.</paso>
<paso>Mezclamos y añadimos el pimentón (1/4 de cucharita de pimentón dulce). Removemos y echamos el tomate picado para refrescar el guiso.</paso>
<paso>Dejamos que todo rehogue a fuego lento, es importante que no apuremos. El secreto de un buen puchero es esperar a que la salsa esté ligada antes de añadir el resto.</paso>
<paso>En ese momento echamos la merluza rehogada, la hoja de laurel, unas cucharadas de agua y un majado de ajo y perejil. Lo dejamos reducir unos 10 minutos.</paso>
</preparacion>
<preparacion>
<titulo>
Cocción y presentación final del arroz con merluza
</titulo>
<paso>Cuando todos los ingredientes estén cocinados incorporamos el caldo y el agua (tres partes por cada parte de arroz).</paso>
<paso>Lo removemos hasta bullir y lo dejamos cocer unos 5 minutos.</paso>
<paso>Entonces echamos el arroz redondo. Removemos todo con suavidad para que se impregne bien del guiso y absorba el sabor.</paso>
<paso>Agregamos el azafrán y corregimos de sal si es necesario.</paso>
<paso>Subimos la temperatura hasta que empiece a hervir y en ese momento la bajamos para que se haga a fuego lento (15 minutos aproximadamente).</paso>
<paso>Si notamos que el arroz está un poco duro y nos quedamos sin líquido siempre podemos añadir más agua. Teniendo en cuenta que el punto final no debe ser muy seco ni demasiado caldoso.</paso>
<paso>Para acabar, apartamos del fuego y lo dejamos reposar 10 minutos con la tapa puesta.</paso>
</preparacion>
</plato>
</platos>

=== emartin85/emartin85.github.io/xml/poapre.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="platos.xsl"?>
<platos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" nombre="Postres" xsi:noNamespaceSchemaLocation="schema.xsd">
<plato id="Aprendiz">
<nombre>Bica mantecada de Trives</nombre>
<imagen>../imagenes/platos/bica.jpg</imagen>
<video>https://www.youtube.com/embed/51sg1AjHH5s</video>
<musica>../audio/9.mp3</musica>
<ingredientes>
<titulo>
Ingredientes para Bica mantecada de Trives
</titulo>
<ingrediente>250 g. de masa de pan (los 4 ingredientes siguientes)</ingrediente>
<ingrediente>Un vaso de agua tibia, 110 ml.</ingrediente>
<ingrediente>2 g. levadura fresca o 4 g. levadura de panadería en polvo</ingrediente>
<ingrediente>Un pellizco de sal (5 g. de sal)</ingrediente>
<ingrediente>200 g. harina de trigo de fuerza</ingrediente>
<ingrediente>Para la bica: 6 huevos M</ingrediente>
<ingrediente>200 g. de manteca de vaca (ya cocida) Se podría sustituir por mantequilla</ingrediente>
<ingrediente>250 g. de harina de trigo (mejor de repostería)</ingrediente>
<ingrediente>450 g. de azúcar + 50 g. para la cobertura</ingrediente>
<ingrediente>Canela en polvo</ingrediente>
<ingrediente>La ralladura de un limón (pequeño)</ingrediente>
</ingredientes>
<introduccion>
La “bica de Trives” es, a día de hoy, uno de los símbolos de este pueblo de la provincia de Ourense.
Aunque comparte su éxito con otros “hits” de la gastronomía local como son los productos de la matanza, la castaña y los buenos vinos de las variedades mencía y godello.
En este pueblo cuyo nombre completo es “A Pobra de Trives” celebran el último fin de semana de julio (este año 27 y 28) la “Festa da Bica de Trives” celebrando una comida popular y la consiguiente degustación de su bica mantecada.
Esta bica es un postre marcado por dos de sus ingredientes imprescindibles: la masa de pan y la manteca de vaca. Estos le aportan una textura consistente, jugosa, con un sabor inconfundible, y alargan su conservación durante 10-12 días en buenas condiciones.
La receta que usaremos nos la ha pasado una conocida de A Pobra de Trives que trabajó en una panadería, donde las suelen guardar bajo llave para preservar su exclusividad en la elaboración.
Es tanto el amor que le tenemos por estas tierras ourensanas que nos dan ganas de comerla en cualquier momento del día: en el desayuno, como postre principal o en la sobremesa acompañada de un buen licor-café, a la hora de la merienda e incluso por la noche acompañada de un rico vaso de leche.
Podemos acompañarla con una mermelada casera de fresa o frambuesa. También un buen maridaje para esta bica es un buen licor café que combina a la perfección con este tipo de bizcochos mantecosos.
</introduccion>
<preparacion>
<titulo>
Preparación de la masa de pan
</titulo>
<paso>Lo conveniente es preparar esta masa de pan varias horas antes, para darle tiempo a crecer, y luego que repose en un lugar templado y oscuro.</paso>
<paso>He utilizado levadura fresca que he comprado en la panadería del barrio. Sale muy barata, a 1 céntimo el gramo. El mayor problema que tiene es su conservación, ya que en el frigorífico tan solo nos aguantará 2-3 días en condiciones.</paso>
<paso>Cuando la compramos tiene color blanco, muy ligeramente amarillo, y con el paso del tiempo se va poniendo amarillo ocre y de textura dura, momento en el que ya estará inservible.</paso>
<paso>En un bol metálico grande, ponemos la harina de base, le hacemos un hueco en el centro y vertemos el agua.</paso>
<paso>Añadimos la levadura fresca desmenuzada y un pellizco de sal, vamos mezclando con los dedos para incorporar el agua totalmente.</paso>
<paso>Amasamos todo con la ayuda de las manos y lo pasamos a una tabla de madera con harina espolvoreada encima.</paso>
<paso>Continuamos amasando con movimientos firmes. Añadiendo un poco de harina si es necesario (ya nos lo va pidiendo la masa), hasta ir formando una bola homogénea. Comprobamos que ya no se nos pega a las manos.</paso>
<paso>El amasado nos llevará aproximadamente unos 15 minutos. Tapamos la bola obtenida con un paño limpio o film transparente y la dejamos reposar mínimo unas dos horas.</paso>
<paso>Durante este tiempo crecerá de tamaño (aprox. el doble), y sabremos cuando está en su punto cuando presionemos con un dedo y la huella vuelve atrás lentamente.</paso>
</preparacion>
<preparacion>
<titulo>
Preparación de la bica de Trives
</titulo>
<paso>Partiendo de manteca de vaca comprada. la colocamos al baño maría para que se ablande. Cuando esté casi líquida la pasamos a un bol grande y la terminamos de disolver con la ayuda de un tenedor.</paso>
<paso>La vamos batiendo mientras se le añade poco a poco el azúcar. Seguimos batiendo y añadimos los huevos uno a uno, hasta integrarlos bien con el resto.</paso>
<paso>Añadimos ahora la masa de pan en trozos poco a poco. Vamos mezclando con un tenedor o varillas metálicas, ayudando a que se deshaga completamente y no queden grumos.</paso>
<paso>Acabada y mezclada la masa, incorporamos ahora la harina poco a poco, que previamente hemos tamizado.</paso>
<paso>Por último añadimos la ralladura de un limón pequeño, para no pasarnos en el sabor que le pueda transmitir a la bica.</paso>
</preparacion>
<preparacion>
<titulo>
Horneado y presentación final de la bica de Trives
</titulo>
<paso>Para hacer este postre he usado un molde metálico de 30 x 21 cm recubierto de papel de horno.</paso>
<paso>Precalentamos el molde en el horno a 180º C durante 10 minutos en la función calor total. Vertemos la masa cremosa en el interior.</paso>
<paso>Mezclamos los 50 gr. de azúcar con canela en polvo. Con la ayuda de un pequeño colador, vamos espolvoreando sobre la masa uniformemente.</paso>
<paso>Horneamos 45-50 minutos en función de la potencia del horno. Si vemos que en la parte final se tuesta demasiado la parte superior, podemos tapar con papel de horno.</paso>
<paso>Como con el resto de bizcochos/bicas, comprobamos con un pincho el punto de elaboración. Debe salir seco y sin dificultad.</paso>
<paso>Retiramos y dejamos enfriar completamente antes de catarla.</paso>
<paso>Es aconsejable hacerla de un día para otro, así cuando la comamos ya habrá enfriado y reposado. Estará realmente deliciosa.</paso>
<paso>Si la preparáis por la tarde, estará perfecta para degustarla en el desayuno del día siguiente.</paso>
</preparacion>
</plato>
</platos>
